import { trpc } from "@/providers/trpc";
import { Link } from "react-router";
import { Calendar, Car, CirclePlus, Gauge, HardHat, Receipt, WalletCards, Wrench } from "lucide-react";

export default function Home() {
  const { data, isLoading } = trpc.fleet.dashboard.useQuery();
  if (isLoading) return <div className="h-64 flex items-center justify-center"><div className="w-8 h-8 border-2 border-orange-500 border-t-transparent rounded-full loading-spinner" /></div>;
  const assets = data?.assets;
  const costs = data?.costs;
  return <div className="animate-fade-in space-y-8">
    <div className="relative overflow-hidden rounded-2xl bg-gradient-to-br from-orange-600/25 via-orange-900/10 to-transparent border border-orange-500/20 p-7 md:p-10"><div className="relative max-w-3xl"><p className="text-orange-400 font-medium mb-2">نظام إدارة صيانة الأسطول</p><h1 className="text-3xl md:text-4xl font-bold">تابع 400 سيارة ومعدة من مكان واحد</h1><p className="text-white/55 text-lg mt-3">ملف كامل لكل أصل، سجل الصيانات والفواتير، العدادات، وتكاليف شهرية وسنوية دقيقة.</p><div className="flex flex-wrap gap-3 mt-6"><Link to="/add-invoice" className="inline-flex items-center gap-2 px-5 py-3 bg-orange-600 hover:bg-orange-500 rounded-lg font-medium"><Wrench className="w-5 h-5" /> تسجيل عملية صيانة</Link><Link to="/vehicles/new" className="inline-flex items-center gap-2 px-5 py-3 bg-white/10 hover:bg-white/15 rounded-lg"><CirclePlus className="w-5 h-5" /> إضافة سيارة أو معدة</Link></div></div></div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><DashboardCard label="إجمالي الأسطول" value={assets?.total || 0} icon={<Car />} /><DashboardCard label="أصول تحت الصيانة" value={assets?.inMaintenance || 0} icon={<HardHat />} /><DashboardCard label="تكلفة الشهر الحالي" value={`${Number(costs?.monthly || 0).toLocaleString("ar-SA")} ر.س`} icon={<Calendar />} highlight /><DashboardCard label={`تكلفة عام ${data?.year || new Date().getFullYear()}`} value={`${Number(costs?.yearly || 0).toLocaleString("ar-SA")} ر.س`} icon={<WalletCards />} /></div>
    <div className="grid grid-cols-1 lg:grid-cols-[1.4fr_.6fr] gap-6"><div><div className="flex items-center justify-between mb-4"><h2 className="text-xl font-bold">أحدث عمليات الصيانة</h2><Link to="/reports" className="text-orange-500 text-sm">التقرير الكامل</Link></div><div className="space-y-3">{data?.recent.length ? data.recent.map((op) => <Link key={op.id} to={`/invoices/${op.id}`} className="glass-card glass-card-hover rounded-xl p-4 flex items-center justify-between gap-4"><div><div className="flex items-center gap-2 text-sm text-white/40"><span>{op.vehicleNumber || "بدون أصل"}</span><span>·</span><span>{new Date(op.date).toLocaleDateString("ar-SA")}</span>{op.odometer !== null && <><span>·</span><span className="flex items-center gap-1"><Gauge className="w-3 h-3" />{op.odometer.toLocaleString("ar-SA")}</span></>}</div><p className="font-semibold mt-1">{op.maintenanceName || op.description || "عملية صيانة"}</p></div><p className="font-bold text-orange-500 whitespace-nowrap">{Number(op.totalAmount).toLocaleString("ar-SA")} ر.س</p></Link>) : <div className="glass-card rounded-xl p-10 text-center text-white/40">لا توجد عمليات صيانة بعد</div>}</div></div><div className="glass-card rounded-xl p-5 h-fit"><h2 className="text-lg font-bold mb-4">ملخص التشغيل</h2><SummaryRow label="أصول تعمل" value={assets?.active || 0} /><SummaryRow label="إجمالي عمليات الصيانة" value={costs?.operations || 0} /><SummaryRow label="إجمالي المصروفات" value={`${Number(costs?.allTime || 0).toLocaleString("ar-SA")} ر.س`} /><Link to="/vehicles" className="mt-5 flex items-center justify-center gap-2 py-2.5 bg-white/5 hover:bg-white/10 rounded-lg"><Receipt className="w-4 h-4" /> فتح سجل الأسطول</Link></div></div>
  </div>;
}

function DashboardCard({ label, value, icon, highlight }: { label: string; value: string | number; icon: React.ReactElement; highlight?: boolean }) { return <div className="glass-card rounded-xl p-5"><div className="w-9 h-9 bg-orange-600/15 text-orange-500 rounded-lg flex items-center justify-center [&>svg]:w-5 [&>svg]:h-5">{icon}</div><p className="text-white/45 text-sm mt-4">{label}</p><p className={`text-2xl font-bold mt-1 ${highlight ? "text-orange-500" : ""}`}>{value}</p></div>; }
function SummaryRow({ label, value }: { label: string; value: string | number }) { return <div className="flex justify-between gap-3 py-3 border-b border-white/5 last:border-0"><span className="text-white/45">{label}</span><strong>{value}</strong></div>; }
